[tool.poetry]
name = "patito"
version = "0.1.0"
description = "A dataframe modelling library built on top of polars and pydantic."
authors = ["Jakob Gerhard Martinussen <jakobgm@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/kolonialno/patito"
repository = "https://github.com/kolonialno/patito"
keywords = ["validation", "dataframe"]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^1.9.0"
polars = "^0.13.25"
pandas = "^1.4.2"
duckdb = {version = "0.3.4", optional = true}
pyarrow = {version = "^7.0.0", optional = true}
coverage = {version = "^6.3.2", extras = ["toml"]}

[tool.poetry.extras]
duckdb = ["duckdb", "pyarrow"]

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-watcher = "^0.2.3"
coverage = "^6.3.2"
pytest-cov = "^3.0.0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["patito"]

[tool.coverage.report]
fail_under = 89
show_missing = true

[tool.isort]
profile = "black"
